# Generated by Django 4.0.6 on 2022-07-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_persona_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='parent',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
